name: MPlugin
version: @version@
main: test.minecraft.mplugin.Main
api-version: 1.13
website: https://github.com/Mikeds36/MPlugin
commands:
  hello:
    description: Hello, World! 문구를 출력합니다.
    usage: |
      /<command>
      Example: /<command> - Hello, World 문구 출력
  gm:
    description: Gamemode를 변경합니다.
    usage: |
      /<command>
      Example: /gm (0, 1, 2, 3) - Gamemode 변경
        0 : Survival
        1 : Creative
        2 : Adventure
        3 : Spectator
  battle:
    description: Start Battle
    usage: |
      /<command>